### ISSUE TITLE
Formatting codes causes unneeded spaces in multiline chat messages

### ISSUE THREAD

**Issue by BAI1** [killjoy1221/tabbychat#14] opened 2015-01-03 16:22 UTC
Multiline in chat works well except where formatting codes are on the additional lines in chat.

After some base level testing I found that formatting codes get converted and then a space added either before or after the formatting code, however only on the additional lines displayed in chat.

I'm using TabbyChat-1.7.10-1.11.1.114-fml.jar with Forge 10.13.0.1180, OptiFine 1.7.10_HD_U_A4, Pixelmon 3.3.8, MapWriter 2.1.1 and InputFix V5. 

As a clearer demonstration of the issue, running the /pl command on my server causes chat to exceed the border of the chat window regardless of the window size. Images below should help to represent the issue.

![2015-01-03_16 20 20](https://cloud.githubusercontent.com/assets/5677835/5602908/85abfcda-9364-11e4-867b-a332d4bc5496.png)
![2015-01-03_16 16 33](https://cloud.githubusercontent.com/assets/5677835/5602909/85ac2bc4-9364-11e4-981a-ed6adadbc7e2.png)
![2015-01-03_16 16 37](https://cloud.githubusercontent.com/assets/5677835/5602910/85b003f2-9364-11e4-89b6-b8b2b9a60e3e.png)
![2015-01-03_16 16 42](https://cloud.githubusercontent.com/assets/5677835/5602911/85b46866-9364-11e4-9a05-666b2fd54522.png)

I noticed this in Build 113 however did not think much of it until I seen the same issue in SirWilli's screenshot on his issue report.
Thanks.
~BAI1

**Comment by Brottweiler** [comment] 2015-01-03 17:14
Duplicate of https://github.com/killjoy1221/tabbychat/issues/13. I can confirm the issue, but I'm not sure what causing it.

**Comment by BAI1** [comment] 2015-01-03 17:15
This is NOT a duplicate of #13 . I do NOT have the DualHotbar mod nor is the issue related to scrolling, tabs or buttons. ~BAI1

**Comment by Brottweiler** [comment] 2015-01-03 18:00
Hmm, sorry then, it looks from the chat formatting that he has the same issue as you. But you are probably correct, sorry!

**Closed** 2015-01-06 02:06 UTC
