### ISSUE TITLE
Tabbychat + DualHotbar issue

### ISSUE THREAD

**Issue by SirWilli** [killjoy1221/tabbychat#13] opened 2015-01-03 12:20 UTC
if I use Tabbychat with DualHotbar it moves the background box up but not the tabs and buttons and the chat goes out of the box:
http://i.imgur.com/8kZ9D0o.png

**Comment by BAI1** [comment] 2015-01-03 17:18
#14 is not a duplicate of this. I am not using the DualHotbar mod, however the chat going out of the box is a symptom of #14 which I noticed in the screenshot provided in this issue. ~BAI1

**Comment by Slind14** [comment] 2015-01-03 19:44
@BAI1 read the ticket text again and take a close look at the picture, it is something else, while your issue is on picture, too.

**Comment by BAI1** [comment] 2015-01-03 19:50
I did look. He mentions it however believes it ot be an issue with the DualHotbar mod. The text going out of the box isn't caused by this issue and does not relate, therefore is separate (while is mentioned here does need its own ticket otherwise people WILL get confused).
~BAI1

**Comment by Slind14** [comment] 2015-01-04 11:51
It is about the tabs being within the chat window and not the text going out of it.

**Comment by BAI1** [comment] 2015-01-04 14:13
That that is not the issue I am having, which is why this isn't a duplicate of #14. This is why I made a separate issue instead of commenting about it here. My issue is there but it is not the topic of this issue report, hence #14. For now 
~BAI1

**Comment by killjoy1221** [comment] 2015-01-06 00:51
What I think it happening is Dualhotbars is transforming GuiNewChat up so the chat doesn't overlap the second hotbar. I'm going to have to transform it back down.

**Closed** 2015-01-06 01:22 UTC
